name: leofindit_ios
description: "A new Flutter project."
publish_to: "none"
version: 1.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.5+1
  sqflite: 2.4.2
  permission_handler: 12.0.1
  feedback: 3.2.0

  flutter_compass: ^0.8.0
  sensors_plus: ^7.0.0
  intl: ^0.20.2
  google_fonts: ^8.0.2
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  http: ^1.6.0
  url_launcher: ^6.3.2
  tutorial_coach_mark: ^1.3.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/leo_splash.png
    - assets/LeoPhoto.jpg

  fonts:

    # (branding / headers)

    - family: Inter
      fonts:
        - asset: assets/Inter/static/Inter_18pt-Regular.ttf
        - asset: assets/Inter/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/Inter/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/Inter/static/Inter_18pt-Bold.ttf
          weight: 700


    # (body / buttons)

    - family: Montserrat
      fonts:
        - asset: assets/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/Montserrat/static/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/Montserrat/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/Montserrat/static/Montserrat-Bold.ttf
          weight: 700